### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by thiagodp** [mlaanderson/database-js-csv#1]
When trying to install it via `npm install`, the following error occurs:
```bash
npm ERR! code E404
npm ERR! 404 Not Found: database-js-csv@latest
```
Do you remember if the project was registered to npm? (I couldn't [find it there](https://www.npmjs.com/search?q=database-js-csv) too)

**Comment by mlaanderson** [comment]
I thought I had published it as well, but apparently not. I'll get that published soon.

**Comment by thiagodp** [comment]
👍

**Comment by mlaanderson** [comment]
Done
